#!/usr/bin/env Rscript
# make_final_supplemental_tables.R
#
# Assembles all supplemental tables for Sun et al. into Final_Supplemental_Tables/.
# Most tables are direct copies of existing files; S2 and S9 require assembly.
# Run from the repository root.
#
# Table → Figure map
# ------------------
# S1   All protein SILAC quantification, long format              S1 Data (master)
# S2   All phosphosite SILAC quantification, long format          S2 Data (master)
# S3   C-starvation proteins ∩ quiescence survival screen        Fig 2  [Drive only]
# S4   P-starvation proteins ∩ quiescence survival screen        Fig 2  [Drive only]
# S5   Normalized protein SILAC ratios, wide format              Fig S2C, S3
# S6   Normalized phosphosite SILAC ratios, wide format          Fig S2D, S4, S5
# S7   ANCOVA results (genotype & nutrient effects)              Fig S3B–E
# S8   WGCNA module membership (wide format)                     Fig 3, S3A
# S9   SILAC isotope incorporation (label validation)            Fig 1B, S1A–C
# S10  Growth curves (OD600 over time)                           Fig 1C
# S11  Bud index over time                                       Fig 1D
# S12  1N DNA content percentage per genotype/condition/time     Fig 1E
# S13  Two-way ANOVA on 1N DNA content trajectories             Fig 1E
# S14  Viability (PI/Syto9) over time                           Fig 1F
# S15  Cell size (FSC-A) over time                              Fig S1D
# S16  Differentially expressed proteins by genotype (WT/rim15Δ) Fig S3B–E, S4
# S17  Differentially expressed proteins by nutrient condition   Fig S3
# S18  WGCNA module eigengenes                                   Fig 3B–C
# S19  Differentially expressed phosphosites by genotype         Fig 4A–F, S4
# S20  Phosphorylation motif enrichment (q < 0.01)              Fig 4C
# S21  Cross-dataset phosphosite overlap membership             Revision Fig R1.3/R2.5
# S22  Cross-dataset phosphoprotein overlap membership          Revision Fig R1.3/R2.5
# S23  Mitochondrial proteome coverage vs reference             Revision Fig R2.7
# S24  Mitochondrial protein log2FC by class                    Revision Fig R2.7
# S25  Cross-dataset proteome coverage (3 studies)             Revision Fig R2.3
# S26  Quiescence-regulation overlap (this study vs Paulo 2015) Revision Fig R2.3
# S27  Proteome overlap detailed: our log2FC vs Paulo 2015 metrics  Revision R2.3
# S28  Phosphosite overlap quantitative: our FC vs published FCs    Revision R2.5

library(tidyverse)

repo_root <- "/Users/david/Projects/Proteome_Rim15_Quiescence"
out_dir   <- file.path(repo_root, "Final_Supplemental_Tables")
dir.create(out_dir, showWarnings = FALSE)

# Helper: copy a single file with a progress message
copy_table <- function(src, table_num, description) {
  dest <- file.path(out_dir, sprintf("Table S%d.csv", table_num))
  src_full <- file.path(repo_root, src)
  if (!file.exists(src_full)) {
    message(sprintf("  MISSING source for S%d: %s", table_num, src))
    return(invisible(NULL))
  }
  file.copy(src_full, dest, overwrite = TRUE)
  message(sprintf("  S%d  %-50s <- %s", table_num, description, src))
}

message("=== Building Final_Supplemental_Tables/ ===\n")

# ── S1: All protein SILAC data, long format ─────────────────────────────────
# Source: tables/master_protein.csv (gitignored; 142 MB; regenerated by
# 01_data_preparation_qc.Rmd). Columns: Protein IDs, Gene names, Protein names,
# Fasta headers, nutrient, samplingTime, replicate, genotype, data, value.
copy_table("tables/master_protein.csv", 1,
           "All protein SILAC data, long format")

# ── S2: All phosphosite SILAC data, long format ──────────────────────────────
# Assembled by pivoting the wide-format S6 source. Keeps per-sample normalized
# ratios (rim15KO and WT channels) and discards the pre-computed WT/rim15KO
# ratio columns (those are in S6/S19). Columns: pSite, Proteins, Leading
# proteins, Gene names, Protein names, genotype, nutrient, timepoint,
# replicate, normalized_ratio.
message("  S2   Assembling long-format phosphosite table from S6 source...")
psite_wide <- read_csv(
  file.path(repo_root, "tables/supplemental/S6_normalized_phosphosite_ratios.csv"),
  show_col_types = FALSE)

id_cols <- c("Proteins", "pSite", "Leading proteins", "Protein names", "Gene names")

psite_long <- psite_wide %>%
  select(any_of(id_cols), matches("^(rim15KO|WT)_[CNP]_T")) %>%
  pivot_longer(
    cols      = matches("^(rim15KO|WT)_[CNP]_T"),
    names_to  = "sample",
    values_to = "normalized_ratio") %>%
  separate(sample,
           into = c("genotype", "nutrient", "timepoint", "replicate"),
           sep  = "_") %>%
  mutate(timepoint_h = as.integer(sub("^T0?", "", timepoint))) %>%
  select(pSite, Proteins, `Leading proteins`, `Gene names`, `Protein names`,
         genotype, nutrient, timepoint_h, replicate, normalized_ratio,
         -any_of("Fasta headers")) %>%
  arrange(pSite, genotype, nutrient, timepoint_h, replicate)

write_csv(psite_long, file.path(out_dir, "Table S2.csv"))
message(sprintf("    -> %d rows written", nrow(psite_long)))

# ── S3 & S4: Quiescence survival overlap tables ───────────────────────────────
# These are small gene-list tables maintained in the Google Drive submission
# folder (PLoS Genetics 3rd Submission/Supplemental Information/) and are not
# present in the local repo. Copy them manually from Drive.
message("  S3  [MANUAL] Copy from Google Drive: quiescence_survival_carbon.csv")
message("  S4  [MANUAL] Copy from Google Drive: quiescence_survival_phosphorus.csv")

# ── S5–S8: Existing supplemental tables ──────────────────────────────────────
copy_table("tables/supplemental/S5_normalized_protein_ratios.csv",  5,
           "Normalized protein SILAC ratios, wide format")
copy_table("tables/supplemental/S6_normalized_phosphosite_ratios.csv", 6,
           "Normalized phosphosite SILAC ratios, wide format")
copy_table("tables/supplemental/S7_ancova_results.csv",             7,
           "ANCOVA results (genotype & nutrient effects)")
copy_table("tables/supplemental/S8_wgcna_module_membership.csv",    8,
           "WGCNA module membership, wide format")

# ── S9: SILAC isotope incorporation (label validation) ───────────────────────
# Source: three MaxQuant proteinGroups files in figure1/.
# Combines (a) prototrophic vs auxotrophic WT in H channel, (b) prototrophic
# vs auxotrophic WT in M channel, and (c) prototrophic WT vs rim15Δ.
# Columns kept: Protein IDs, Fasta headers, comparison, normalized_ratio_mean,
# normalized_ratio_rep1, normalized_ratio_rep2 (where available).
# Contaminants (CON__) and decoy hits (+) are excluded.
message("  S9   Assembling SILAC incorporation table from figure1/ MaxQuant files...")

read_mq <- function(path, sep = ",") {
  read_delim(path, delim = sep, show_col_types = FALSE,
             name_repair = "minimal") %>%
    filter(is.na(Reverse) | Reverse != "+",
           is.na(`Potential contaminant`) | `Potential contaminant` != "+",
           !grepl("^CON__", `Protein IDs`))
}

# (a) Pro-WT H channel vs Auxo-WT H channel (replicate mean + per-rep)
pro_auxo_H <- read_mq(file.path(repo_root, "figure1/proteinGroups_pro_auxo_H.csv")) %>%
  transmute(
    `Protein IDs`,
    comparison            = "ProtoWT_H_vs_AuxoWT_H",
    normalized_ratio_mean = `Ratio H/L normalized`,
    normalized_ratio_rep1 = `Ratio H/L normalized 4`,
    normalized_ratio_rep2 = `Ratio H/L normalized 5`)

# (b) Pro-WT M channel vs Auxo-WT M channel
pro_auxo_M <- read_mq(file.path(repo_root, "figure1/proteinGroups_pro_auxo_M.csv")) %>%
  transmute(
    `Protein IDs`,
    comparison            = "ProtoWT_M_vs_AuxoWT_M",
    normalized_ratio_mean = `Ratio H/L normalized`,
    normalized_ratio_rep1 = `Ratio H/L normalized 4`,
    normalized_ratio_rep2 = `Ratio H/L normalized 5`)

# (c) Pro-WT (H channel) vs rim15Δ (M channel)
pro_rim15 <- read_mq(file.path(repo_root, "figure1/proteinGroups_rim15_HM.csv")) %>%
  transmute(
    `Protein IDs`,
    comparison            = "ProtoWT_H_vs_rim15_M",
    normalized_ratio_mean = `Ratio H/M normalized`,
    normalized_ratio_rep1 = `Ratio H/M normalized 1`,
    normalized_ratio_rep2 = `Ratio H/M normalized 2`)

s9 <- bind_rows(pro_auxo_H, pro_auxo_M, pro_rim15) %>%
  arrange(comparison, `Protein IDs`)

write_csv(s9, file.path(out_dir, "Table S9.csv"))
message(sprintf("    -> %d rows written", nrow(s9)))

# ── S10–S24: Direct copies ────────────────────────────────────────────────────
copy_table("figure1/growth_long.csv",                          10,
           "Growth curves (OD600/counts vs time)")
copy_table("figure1/budindex_short.csv",                       11,
           "Bud index vs time")
copy_table("revision3/output/dna_1n_percent_summary.csv",      12,
           "1N DNA content percentage per genotype/condition/time")
copy_table("revision3/output/dna_1N_anova.csv",                13,
           "Two-way ANOVA on 1N DNA content trajectories")
copy_table("figure1/viability.csv",                            14,
           "Viability (PI/Syto9) vs time")
copy_table("revision3/output/cellsize_summary.csv",            15,
           "Cell size (FSC-A) vs time")
copy_table("tables/DE_proteins_byGenotype.csv",                16,
           "Differentially expressed proteins by genotype")
copy_table("tables/DE_proteins_byNutrient.csv",                17,
           "Differentially expressed proteins by nutrient")
copy_table("tables/wgcna_module_eigengenes.csv",               18,
           "WGCNA module eigengenes")
copy_table("tables/DE_pSites_byGenotype.csv",                  19,
           "Differentially expressed phosphosites by genotype")
copy_table("tables/motif_sig(q<0.01).csv",                     20,
           "Phosphorylation motif enrichment (q < 0.01)")
copy_table("revision3/output/phosphosite_membership.csv",      21,
           "Cross-dataset phosphosite overlap membership")
copy_table("revision3/output/phosphoprotein_membership.csv",   22,
           "Cross-dataset phosphoprotein overlap membership")
copy_table("revision3/output/mito_coverage_table.csv",         23,
           "Mitochondrial proteome coverage vs reference")
copy_table("revision3/output/mito_class_log2fc.csv",           24,
           "Mitochondrial protein log2FC by subclass")
copy_table("revision3/output/proteome_coverage.csv",           25,
           "Cross-dataset proteome coverage (this study, Paulo 2015, den Ridder 2023)")
copy_table("revision3/output/proteome_regulation_overlap.csv", 26,
           "Quiescence-regulation overlap (rim15Δ-regulated vs Paulo 2015 quiescent-enriched)")
copy_table("revision3/output/proteome_overlap_detailed.csv",     27,
           "Proteome overlap detailed: our log2FC + Paulo 2015 ratio and p-value")
copy_table("revision3/output/phosphosite_overlap_quantitative.csv", 28,
           "Phosphosite overlap quantitative: our log2FC/q + Li2019 + Plank fold-changes")

# ── Summary ───────────────────────────────────────────────────────────────────
files_written <- list.files(out_dir, pattern = "^Table S.*\\.csv$")
message(sprintf("\nDone. %d tables written to %s/", length(files_written), out_dir))
message("Tables requiring manual steps:")
message("  S3, S4  — copy from Google Drive submission folder")
